node {
  name     = "emqx@127.0.0.1"
  cookie   = "urban-emqx-secret"
  data_dir = "/opt/emqx/data"
}

cluster {
  name               = urban
  discovery_strategy = manual
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"
}

listeners.ws.default {
  bind = "0.0.0.0:8083"
}

allow_anonymous = true
authorization.no_match = allow

dashboard {
  listeners.http {
    bind = 18083
  }
  default_username = "admin"
  default_password = "urban123"
}